# Generated by Django 4.2.13 on 2024-05-27 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablety', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producent', models.CharField(max_length=65)),
                ('model', models.TextField(max_length=65)),
                ('liczba_sztuk', models.PositiveSmallIntegerField(default=1)),
                ('cena', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='zdjecia')),
                ('dostawca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablety.dostawca')),
            ],
        ),
    ]
