# Generated by Django 4.2.13 on 2024-05-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablety', '0002_produkt'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='opis',
            field=models.TextField(default='', max_length=65),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='cena',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='model',
            field=models.CharField(max_length=65),
        ),
    ]
