# Generated by Django 4.2.13 on 2024-05-27 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablety', '0003_produkt_opis_alter_produkt_cena_alter_produkt_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recenzja', models.TextField(blank=True, default='')),
                ('gwiazdki', models.PositiveSmallIntegerField(default=5)),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablety.produkt')),
            ],
        ),
    ]
